### ISSUE TITLE
[Feature] Render non-ASCII? characters correctly

### ISSUE THREAD

**Issue by kometenstaub** [valentine195/obsidian-image-window#4]
Currently, non-ASCII characters are not rendered correctly.

Example:

`passé`, `chère`

![image](https://user-images.githubusercontent.com/83140328/157470816-e8ca1394-069f-43a3-a1b4-ce7bf74d973b.png)

It also seems to affect ASCII characters like `§`.

![image](https://user-images.githubusercontent.com/83140328/157471225-92359bd7-e815-4093-a45f-250d11db06ad.png)

**Comment by JustusPan** [comment]
+1 vote for this. Unicode support is required.

**Comment by gkavboy** [comment]
I confirm that unicode text do not display correctly

**Comment by Hunter-Bobeck** [comment]
If this plugin could do this it would be worth using!

**Comment by valentine195** [comment]
This plugin is going to be deprecated / no longer maintained. Obsidian has multi-window support natively now.
